service: deepspeech-lambda-demo
app: tflambda
org: lukasgrasse

provider:
  name: aws
  runtime: python3.6
  stage: dev
  region: us-east-1

functions:
  infer:
    handler: infer.inferHandler
    timeout: 30
    events:
      - http:
          path: infer
          method: post
      
plugins:
  - serverless-python-requirements
  - serverless-offline

custom:
  pythonRequirements:
    dockerizePip: true
    slim: true
    zip: true